### ISSUE TITLE
xcb

### ISSUE THREAD

**Issue by MaikKlein** [ParticlePeter/ErupteD#1]
Regarding your post

> ```
>     {
>         "name"          :   "dub-platform-xcb",
>         "versions"      :   [ "VK_USE_PLATFORM_XCB_KHR" ],
>         "dependencies"  :   {
>             "xcb-d"     : "~>2.1.0+1.11.1"
>     },
> ```
> 
> In your project dub.json add:
> 
>   "subConfigurations" :   {
>       "erupted"   :   "dub-platform-xcb",
>   },

I am not sure if that works. Is it possible to combine configurations in dub? For example I would need `with-derelict-loader` and `dub-platform-xcb`.

Temporarily I just hacked it to this

```
{
            "name"          :   "dub-platform-xcb",
            "versions"      :   [ "VK_USE_PLATFORM_XCB_KHR", "ERUPTED_FROM_DERELICT" ],
            "dependencies"  :   {
                "xcb-d"     : "~>2.1.0",
                "derelict-util" : "~>2.0.4"
            },
},

```

**Comment by ParticlePeter** [comment]
Funny Thing is that I am creating exacly that just right now.
There will be `"dub-platform-xcb"` and `"dub-platform-xcb-derelict-loader"` configurations.

In any case, does your edit work?
Why did you use `"xcb-d"     : "~>2.1.0"`
instead of `"xcb-d"     : "~>2.1.0+1.11.1"` , is the second part `+1.11.1` optional?

 If it works I will create a new version.

**Comment by MaikKlein** [comment]
+1.11.1 seems to be optional and yes what I have posted above works. I just realized that I need xlib instead of xcb :d.

**Comment by ParticlePeter** [comment]
I did create versions for `XCB`, `XLIB` and `Wayland`. It would be great if you could any of them. Just pushed erupted Version 1.3.0

**Comment by MaikKlein** [comment]
Does dub need a while to recognize the update?

Because if I do `dependency "erupted" version="~>1.3.0"`

> Could not find a valid dependency tree configuration:

It seems to be on https://code.dlang.org/packages/erupted though, not sure what is going on.

**Comment by ParticlePeter** [comment]
Unfortunately it does. The versions are listed shortly after pushing, but dub utility needs some time to register the change. Don't know why and don't know how much time.

**Comment by MaikKlein** [comment]
Okay it is live now and it seems to work.
