### ISSUE TITLE
Allocating Vulkan handles fails with DMD -profile=gc

### ISSUE THREAD

**Issue by GoaLitiuM** [ParticlePeter/ErupteD#11]
This simple line is enough to reproduce the bug when building a project with DMD on Windows with -profile=gc :
`VkPhysicalDevice[] devices = new VkPhysicalDevice[1];`

Produces the following:
`core.exception.OutOfMemoryError@src/core/exception.d(700): Memory allocation failed`

This seems to be a bug in DMD itself, but it can be worked around by changing the 40th line in erupted/types.d from:
`enum VK_DEFINE_HANDLE( string name ) = "struct " ~ name ~ "_handle; alias " ~ name ~ " = " ~ name ~ "_handle*;";`
to:
`enum VK_DEFINE_HANDLE( string name ) = "struct " ~ name ~ "_handle {}; alias " ~ name ~ " = " ~ name ~ "_handle*;";`
... by declaring the structure with empty brackets, but I'm not sure if this causes any side effects. Building and running a simple Vulkan program which displays a triangle did run succesfully with this change.

**Comment by ParticlePeter** [comment]
Hi, I am sorry for the late replied, I reallocated to another country and get my Internet connection just right now. I will look into this, try to reproduce your issue, and test your solution.

Have you filed a bug with bugzilla already? Seems quite wired to me that the issue happens only when using the GC profiler, and that I should fix the library for that corner case.

**Comment by GoaLitiuM** [comment]
I filed the bug report here: https://issues.dlang.org/show_bug.cgi?id=19191

**Comment by ParticlePeter** [comment]
I read again through your bug report, and it's kind of wired. DLang has nothing official to do with ErupteD. So what you need to do is to create a case which does not depend on ErupteD. It should be pretty straight forward to create that issue from scratch and post it independently from ErupteD.

**Comment by GoaLitiuM** [comment]
The bug report does not depend on Erupted, I just happened to use the same structure names in the given example code. You can copy that whole snippet and run it yourself without installing any packages, or here: https://run.dlang.io/is/B5soAj

**Comment by ParticlePeter** [comment]
Please read properly what I wrote. I know that the bug has nothing to do with erupted. But why did you put erupted and Vulkan structures into your bug report?

Please now read carefully: your report READS LIKE you found a bug in erupted and report it at dlang bugzilla.

When you report a language bug, you need to report it independent of ANY library, including phobos. Otherwise it wouldn't be clear if it is a LANGUAGE bug.
So if you add a repro-case in code, it should be pure D without any imports.

**Comment by GoaLitiuM** [comment]
Maybe it's you who must read the bug report more closely.

The title of the bug report clearly says it's an issue with opaque handles, so no confusion here. The code snippet which demonstrates the issue clearly reproduces the issue without any external imports or libraries. Only thing that seems to bug you is the name of the structures, which are really not relevant to the bug in question. It just shows there is a real world case out there where the `-profile=gc` switch does not work correctly. Anyone who reads these bug reports can see past the origin of the bug and focus on the code that is causing it. I'm not going to create a new bug report just to remove the references to ErupteD.

And on top of that, I had figured out the workaround to fix the bug in library level, so I'm not sure why this seemingly small change has not been fixed in ErupteD itself.
