### ISSUE TITLE
Support for VK_KHR_mir_surface should be removed

### ISSUE THREAD

**Issue by gfxstrand** [ParticlePeter/ErupteD#12]
See also: https://github.com/KhronosGroup/Vulkan-Docs/issues/814

**Comment by ParticlePeter** [comment]
Erupted is auto-generated from vk.xml. Any action applied that file will be reflected in erupted, no extra work should be required.
ErupteD is derived from [dvulkan](https://github.com/ColonelThirtyTwo/dvulkan/issues/23), which, AFAIK, is not being developed any more.
