### ISSUE TITLE
Property helpers for array

### ISSUE THREAD

**Issue by ghost** [ParticlePeter/ErupteD#14]
There's a lot of "array" elements in the structs that could use helper functions to set from d arrays.
```D
uint32_t xCount; // Usually have this form where "x" is some common name between the two
void* pXs;

// helps to convert to and from
void[] xs() { return pXs[0 .. xCount]; }
void xs( void[] value ) { pXs = value.ptr; xCount = value.length32; }
```

**Comment by ParticlePeter** [comment]
I agree, but this is not the task of a binding, but rather of a wrapper calling the bound functions. Such a wrapper could then become even more intelligent. Besides, the binding is auto generated, following the C generator. Feel free to extend the [V-Erupt](https://github.com/ParticlePeter/V-Erupt) generator your self, we then can figure out how to merge the result with ErupteD. You can also take a look on the Vulkan CPP generator.

**Comment by ParticlePeter** [comment]
I agree, but this is not the task of a binding, but rather of a wrapper calling the bound functions. Such a wrapper could then become even more intelligent. Besides, the binding is auto generated, following the C generator. Feel free to extend the [V-Erupt](https://github.com/ParticlePeter/V-Erupt) generator your self, we then can figure out how to merge the result with ErupteD. You can also take a look on the Vulkan CPP generator.

**Comment by ParticlePeter** [comment]
Can this be closed?
