### ISSUE TITLE
Can't compile any code

### ISSUE THREAD

**Issue by wusikijeronii** [ParticlePeter/ErupteD#15]
Hello. I can't compile code with this package.
For first I fetched this package, add dependencies to my dub.json and it was successful. Then I tried to build or run that, but I got the error:
`Main package must not have target type "sourceLibrary".` 
Okay, so then I copied sources to import folder (on the compile folder). And now I see autocompletion, but I can't compile my code. I tried ldc2 and DMD compilers.
Other dub packages work fine, My code:
```
import std.stdio;
import std.range;
import std.array;
import std.algorithm;
import std.exception;
import std.conv;
import std.string;
import erupted;
import erupted.vulkan_lib_loader;


void main() {

	// load global level functions	// not part of erupted package, as not part of original vulkan
	loadGlobalLevelFunctions;
	VkInstanceCreateInfo info = {};
	VkInstance instance;
	if (vkCreateInstance(&info,null, &instance) == VK_SUCCESS) {
		writeln("Test");
	}
}
```
Via ldc2 I get the error: 
```
lld-link: error: undefined symbol: lld-link: error: undefined symbol: _D7erupted17vulkan_lib_loader24loadGlobalLevelFunctionsFNbNiPOS4core4stdc5stdio6_iobufZb
>>> referenced by app.obj:(_Dmain)

lld-link: error: undefined symbol: _D7erupted9functions16vkCreateInstancePWNbNiPxSQBt5types20VkInstanceCreateInfoPxSQDbQBi21VkAllocationCallbacksPPSQEhQCo17VkInstance_handleZEQFiQDp8VkResult
>>> referenced by app.obj:(_Dmain)
Error: linking with LLD failed
```
Via DMD I get the error: 
```
import path[0] = C:\D\dmd2\windows\bin\..\..\src\phobos
import path[1] = C:\D\dmd2\windows\bin\..\..\src\druntime\import
```
I also tried to run examples from this package but I just get same errors in several times more.

**Comment by ParticlePeter** [comment]
> Hello. I can't compile code with this package.
For first I fetched this package, add dependencies to my dub.json and it was successful. Then I tried to build or run that, but I got the error:
Main package must not have target type "sourceLibrary".

Sounds like your project's dub.json/sdl is not configured properly. Check if you specified  targetType as "sourceLibrary" instead of "executable". If I am wrong please paste your project's dub file or repository link here.

> Okay, so then I copied sources to import folder (on the compile folder).

There should never be need for that. From the DMD error you posted, which is incomplete btw, I assume that the modules could not be found and are probably copied to the wrong location. In any case I recommend removing the copies again. If the suggested solution above does not work, please paste the full DMD error here.

Not clear what the LDC issue is, as it is an linker error. When it persists after the fix above I'll need some time to dive into this. Most helpful here would be a repository link.

> I also tried to run examples from this package but I just get same errors in several times more.

So after erupted has been fetched as being a dependency, you tried to run the examples?
`dub run erupted:devices`
Can you please try this once more with DMD and paste the full error here? Also with your system info (OS, GPU).

**Comment by wusikijeronii** [comment]
> > Hello. I can't compile code with this package.
> > For first I fetched this package, add dependencies to my dub.json and it was successful. Then I tried to build or run that, but I got the error:
> > Main package must not have target type "sourceLibrary".
> 
> Sounds like your project's dub.json/sdl is not configured properly. Check if you specified targetType as "sourceLibrary" instead of "executable". If I am wrong please paste your project's dub file or repository link here.
> 
> > Okay, so then I copied sources to import folder (on the compile folder).
> 
> There should never be need for that. From the DMD error you posted, which is incomplete btw, I assume that the modules could not be found and are probably copied to the wrong location. In any case I recommend removing the copies again. If the suggested solution above does not work, please paste the full DMD error here.
> 
> Not clear what the LDC issue is, as it is an linker error. When it persists after the fix above I'll need some time to dive into this. Most helpful here would be a repository link.
> 
> > I also tried to run examples from this package but I just get same errors in several times more.
> 
> So after erupted has been fetched as being a dependency, you tried to run the examples?
> `dub run erupted:devices`
> Can you please try this once more with DMD and paste the full error here? Also with your system info (OS, GPU).

About dub: do you mean dub in my app folder, right? (That dub file in attachment) I added targetType to my dub file but I still can't build erupted via dub.  I get the same error. About dmd, yes I forgot to copy erupted to import and Phobos folders as I did via ldc2.
I copied erupted to these folders and now I get errors:
```
PS D:\Downloads\ErupteD-master\examples> dmd layers.d
OPTLINK (R) for Win32  Release 8.00.17
Copyright (C) Digital Mars 1989-2013  All rights reserved.
http://www.digitalmars.com/ctg/optlink.html
layers.obj(layers) 
 Error 42: Symbol Undefined __D7erupted9functions17vkDestroyInstancePWNbNiPSQBt5types17VkInstance_handlePxSQCyQBf21VkAllocationCallbacksZv
layers.obj(layers)
 Error 42: Symbol Undefined __D7erupted5types17VkLayerProperties6__initZ
layers.obj(layers)
 Error 42: Symbol Undefined __D7erupted9functions26loadInstanceLevelFunctionsFNbNiPSQCb5types17VkInstance_handleZv
layers.obj(layers)
 Error 42: Symbol Undefined __D7erupted9functions16vkCreateInstancePWNbNiPxSQBt5types20VkInstanceCreateInfoPxSQDbQBi21VkAllocAEEBAF2D593A8E1163962D5ACC5EF774
layers.obj(layers)
 Error 42: Symbol Undefined __D7erupted5types15VK_MAKE_VERSIONFNaNbNikkkZk
layers.obj(layers) 
 Error 42: Symbol Undefined __D7erupted9functions34vkEnumerateInstanceLayerPropertiesPWNbNiPkPSQCm5types17VkLayerPropertiesZEQDqQBe8VkResult
layers.obj(layers)
 Error 42: Symbol Undefined __D7erupted17vulkan_lib_loader24loadGlobalLevelFunctionsFNbNiPOS4core4stdc5stdio6_iobufZb
layers.obj(layers)
 Error 42: Symbol Undefined __D7erupted5types16VK_VERSION_PATCHFNaNbNikZk
layers.obj(layers)
 Error 42: Symbol Undefined __D7erupted5types16VK_VERSION_MINORFNaNbNikZk
layers.obj(layers)
 Error 42: Symbol Undefined __D7erupted5types16VK_VERSION_MAJORFNaNbNikZk
layers.obj(layers)
 Error 42: Symbol Undefined __D7erupted9functions32vkEnumerateDeviceLayerPropΘtiesPWNbNiPSQCi5types23VkPhysicalÇå▓_handlePkÇâªDuQBm17VkÇÅ╟ZEQEvQCn8VkResult
layers.obj(layers)
 Error 42: Symbol Undefined __D7erupted9functions26vkEnumeratePhysicalDev±esPWNbNiPSQCc5types17VkInstance_hΘdlePkPÇâíDjQBh23VkÇÄ┬ÇçñZEQEqQCo8VkResult
Error: linker exited with status 12
```
I use win10 x64. My GPU is nVidia RTX 2070.
[dub.zip](https://github.com/ParticlePeter/ErupteD/files/3673271/dub.zip)

**Comment by wusikijeronii** [comment]
Oooh. If I run dub run erupted:devices it works. Thanks/. I've understood. Sorry for the dumb question. My carelessness.

**Comment by ParticlePeter** [comment]
Yes I see. Maybe my wording above was wrong. You need to use `"targetType": "executable"` instead of `"targetType": "sourceLibrary"`.
Full dub.json:
```
{
    "authors": [
        "WJ"
    ],
    "copyright": "Not",
    "dependencies": {
        "dcd": "~>0.12.0",
        "dfix": "~>0.3.5",
        "dfmt": "~>0.10.1",
        "dscanner": "~>0.8.0",
        "erupted": "~>2.0.43+v1.1.123"
    },
    "targetType": "executable",
    "description": "The test app",
    "license": "proprietary",
    "name": "app"
}
```

Now once  more. __You are not supposed to copy source files around.__ DUB does all the module import resolution for you. All you need to do is set the dependencies.
__Never__ copy project  source files into DMD or LDC folders ... unless you know what you are doing and have a good purpose for it. Your's isn't.

You don't need to build libraries yourself, DUB is doing that for you. You just need to build your project.

**Comment by wusikijeronii** [comment]
> Yes I see. Maybe my wording above was wrong. You need to use `"targetType": "executable"` instead of `"targetType": "sourceLibrary"`.
> Full dub.json:
> 
> ```
> {
>     "authors": [
>         "WJ"
>     ],
>     "copyright": "Not",
>     "dependencies": {
>         "dcd": "~>0.12.0",
>         "dfix": "~>0.3.5",
>         "dfmt": "~>0.10.1",
>         "dscanner": "~>0.8.0",
>         "erupted": "~>2.0.43+v1.1.123"
>     },
>     "targetType": "executable",
>     "description": "The test app",
>     "license": "proprietary",
>     "name": "app"
> }
> ```
> 
> Now once more. **You are not supposed to copy source files around.** DUB does all the module import resolution for you. All you need to do is set the dependencies.
> **Never** copy project source files into DMD or LDC folders ... unless you know what you are doing and have a good purpose for it. Your's isn't.
> 
> You don't need to build libraries yourself, DUB is doing that for you. You just need to build your project.

Okay, I've tried that way, but I've got a fail. Again. =((
I deleted erupted folder from import folder in compilator and I just replaced my dub to suggested by yours but I get the same error:  
```
Building package erupted in C:\Users\home\AppData\Local\dub\packages\erupted-2.0.43_v1.1.123\erupted\
Main package must not have target type "sourceLibrary". Cannot build.
```
I also tried to edit erupted dub file and replace all sourceLibrary to executable (for nothing bad. Just for the test) and I got the error: 
```
erupted 2.0.43+v1.1.123: building configuration "library"...
Linking...
lld-link: error: subsystem must be defined
C:\ldc2-1.18.0-beta1-windows-x64\bin\ldc2.exe failed with exit code 1.
```
Okay, then I tried to make dub file similar like example dub file:
```
`{
    "authors": [
        "WJ"
    ],
    "copyright": "Not",
    "dependencies": {
        "dcd": "~>0.12.0",
        "dfix": "~>0.3.5",
        "dfmt": "~>0.10.1",
        "dscanner": "~>0.8.0",
        "erupted": "~>2.0.43+v1.1.123"
	},
    "targetType": "sourceLibrary",
    "description": "The test app",
    "license": "proprietary",
	"name": "erupted",
	"subPackages"   : [
        {
            "name"              :   "app",
            "description"       :   "Simple Vulkan example",
            "targetType"        :   "executable",
            "sourceFiles"       :   [ "source/app.d" ],
            "dependencies"      :   {
                "erupted"           :   { "path": "." }
			}
		}
		]
}
```
But I got only that error:
```
Building package erupted:app in D:\Documents\Programming\Projects\MyApp\
Selected package libdparse 0.8.8 does not match the dependency specification ~>0.13.0 in package libddoc. Need to "dub upgrade"?
Selected package libdparse 0.8.8 does not match the dependency specification ~>0.13.0 in package dsymbol. Need to "dub upgrade"?
Selected package libdparse 0.8.8 does not match the dependency specification ~>0.13.0 in package dscanner. Need to "dub upgrade"?
Selected package libdparse 0.8.8 does not match the dependency specification ~>0.13.0 in package dcd. Need to "dub upgrade"?
Selected package libdparse 0.8.8 does not match the dependency specification ~>0.11.4 in package dfmt. Need to "dub upgrade"?
Detected dependency cycle: erupted->erupted:
```
And yes, I've tried dub upgrade. Without erupted, dub build works.
If I enter the command `dub upgrade` I get that error:
```
Unresolvable dependencies to package libdparse:
  dfix 0.3.5 depends on libdparse ~>0.8.7
  erupted ~master depends on libdparse ~>0.13.1
```
This error I get If my dub is like in the example dub, but if I use dub file as in your previous  message, I get the error , despite on without erupted libs and dependencies I don't get that error:
```
dsymbol 0.9.0: building configuration "library"...
C:\Users\home\AppData\Local\dub\packages\dsymbol-0.9.0\dsymbol\src\dsymbol\conversion\package.d(148,31): Error: undefined identifier MissingFunctionBody
C:\Users\home\AppData\Local\dub\packages\dsymbol-0.9.0\dsymbol\src\dsymbol\conversion\package.d(165,33): Error: undefined identifier SpecifiedFunctionBody
```

**Comment by ParticlePeter** [comment]
Which command and arguments do you use to compile Please post theme here.

> I also tried to edit erupted dub file and replace all `sourceLibrary` to executable (for nothing bad. Just for the test) and I got the error:

You should not do these things. Dub libraries are usually set up properly to simply use them.
I recommend you read DUB documentation, especially:
https://dub.pm/package-format-json.html#target-types

Only the main project, your project, must have `"targetType": "executable"`. The other targets should be some the other listed.

> Unresolvable dependencies to package libdparse:
  dfix 0.3.5 depends on libdparse ~>0.8.7
  erupted ~master depends on libdparse ~>0.13.1

Erupted has no dependencies. I think you screwed up your project dub and erupted library beyond any chance of repair. I recommend you restart from scratch:

1. Delete all cached libraries, make sure to look into the dub cache folder that all are gone.
2. Use the dub.json for your project which I have posted above.
3. Make sure `"targetType": "executable"` is used in that dub.json file.
4. __Build only your project.__ Don't build any library and don't edit their dub.json or dub.sdl.

**Comment by wusikijeronii** [comment]
> Which command and arguments do you use to compile Please post theme here.
> 
> > I also tried to edit erupted dub file and replace all `sourceLibrary` to executable (for nothing bad. Just for the test) and I got the error:
> 
> You should not do these things. Dub libraries are usually set up properly to simply use them.
> I recommend you read DUB documentation, especially:
> https://dub.pm/package-format-json.html#target-types
> 
> Only the main project, your project, must have `"targetType": "executable"`. The other targets should be some the other listed.
> 
> > Unresolvable dependencies to package libdparse:
> > dfix 0.3.5 depends on libdparse ~>0.8.7
> > erupted ~master depends on libdparse ~>0.13.1
> 
> Erupted has no dependencies. I think you screwed up your project dub and erupted library beyond any chance of repair. I recommend you restart from scratch:
> 
> 1. Delete all cached libraries, make sure to look into the dub cache folder that all are gone.
> 2. Use the dub.json for your project which I have posted above.
> 3. Make sure `"targetType": "executable"` is used in that dub.json file.
> 4. **Build only your project.** Don't build any library and don't edit their dub.json or dub.sdl.

I figured it out. Do you know what wrong was? - Dependies order. I've deleted all packages in dub folder - same error. Okay, then I've deleted all dependies besides erupted and yeah - it works. Okay, then I add other dependies from one to another (dfix, dscanner and etc) and it works. Just my previous order: (Don't know why dub build dependies in that order in despite on .dub fiile has opposite order)
        "erupted": "~>0.12.0",
        "dscanner": "~>0.3.5",
        "dfmt": "~>0.10.1",
        "dfix": "~>0.8.0",
        "dcd": "~>2.0.43+v1.1.123"
Now dependies build in opposite order and it works. I think this issue can be closed.

**Comment by ParticlePeter** [comment]
Good to hear, but that's wired. You might want report that issue at the dub forum. But also as a note, I did not notice the libraries you were importing into your project, but they actually do not male sense to combine with a Vulkan project. 
You would normally use these libarries ON your source code, but would not import them INTO your source code: dscanner, dfmt, dfix.
And dcd is used by text editors (e.g. sublime) and IDE's as plugin or built in.

Anyways, closing.
