### ISSUE TITLE
_module not module_?

### ISSUE THREAD

**Issue by JonathanILevi** [ParticlePeter/ErupteD#16]
Isn't the standard for name clashes to add an `_` to the end?  The `_` at the beginning is confusing because of some languages (e.g. Python) standard to use that for private variables.

(Like in `VkPipelineShaderStageCreateInfo`.)

Maybe not a big deal, and maybe that is D's standard.  I just thought it was weird and had to look it up when `module_` did not work.

**Comment by ParticlePeter** [comment]
I also don't like this variant too much. ErrupteD originally branched from D-Vulkan, and _module was already used there. I would argue that now it's kind of too late to change it. But I am also not aware of any standard which you are mentioning, I think it boils down to taste.

**Comment by JonathanILevi** [comment]
The preceding underscore is defined in PEP8 (which is the general Python standards) for private/internal.  And a succeeding underscore for name clashes.  https://dbader.org/blog/meaning-of-underscores-in-python

This has also been the standard in C++ and has a similar understanding in C# 
 https://stackoverflow.com/a/3136618

It likely is too late for Erupted, it is not a meaningful enough to warrant a breaking change.  It just kind of subtly irks me.  Maybe adding an `alias module_ = _module` to those structs would be appropriate.

**Comment by ParticlePeter** [comment]
Your suggestion was also on my mind but, I believed for quite some time that member variables cannot be aliased, had problems with it in the past. Boy was i wrong, confirmed that now. Will add those aliases to the next release.

**Comment by JonathanILevi** [comment]
Cool, thanks.
