### ISSUE TITLE
Compiler error when attempting to use platform extensions

### ISSUE THREAD

**Issue by david7a68** [ParticlePeter/ErupteD#18]
Using the example code provided in `examples/platform/vulkan_windows.d`, the compiler is unable to link the mixin.

The Platform_Extensions mixin incorrectly declares both versions of `loadDeviceLevelFunctions` to be `extern(System)`. The names do not get mangled, and so collide in the linker.

I attempted to find a fix, but could not identify where the file is generated in erupt.py.

The simplest solution apparent to me would be to move `extern(System)` into the `static foreach` where the extensions are enumerated.

**Comment by ParticlePeter** [comment]
Have you tried using `vulkan_windows.loadDeviceLevelFunctions` instead?

**Comment by david7a68** [comment]
I don't understand your suggestion. Isn't `vulkan_windows.loadDeveiceLevelFunctions` contained within the `Platform_Extensions` mixin?

**Comment by ParticlePeter** [comment]
No, the moment you use the mixin, it becomes part of the module where you mixed it in.
See 3. in https://dlang.org/spec/template-mixin.html

Mixins are not linked, they are manifested code. Your error is also not a linker error but a compiler error. The compiler does not know which `loadDeviceLevelFunction` to use, so you tell him with specifying the embedding module, in the example case `vulkan_windows`.
See 4. in https://dlang.org/spec/module.html#name_lookup.

Another, maybe easier, way to fix your issue might be this (as stated in the link above):
```
import erupted;
import vulkan_windows:
alias loadDeviceLevelFunction = vulkan_windows.loadDeveiceLevelFunctions;
```
And then you can use `loadDeviceLEvelFunction` later without prefix, it will chose the one from module` vulkan_windows`.

**Comment by david7a68** [comment]
Apologies for the delay.

Thank you for your suggestion, but it still doesn't work. Here I have a module that is identical to vulkan_windows:

```D
/+ dub.sdl:
	name "vk"

	dependency "erupted" version="*"
+/

import core.sys.windows.windows;
import erupted.platform_extensions;

mixin Platform_Extensions!USE_PLATFORM_WIN32_KHR;
```

It fails to compile, offering the error:
```
Error: Function type does not match previously declared function with the same mangled name: loadDeviceLevelFunctions
       Previous IR type: void (%erupted.types.VkInstance_handle*)
       New IR type: void (%erupted.types.VkDevice_handle*)
```

**Comment by david7a68** [comment]
I found it! Months later...

It seems like the issue is with the way `loadDeviceFunctions` is declared twice while under the `extern (System)` marker in `erupted.platform_extensions`. I tried modifying those with `extern (D)` and it worked fine.

```D
/*extern ( D )*/ void loadDeviceLevelFunctions( VkInstance instance ) { ... }
```

and 

```D
/*extern ( D )*/ void loadDeviceLevelFunctions( VkDevice device ) { ... }
```

**Comment by ParticlePeter** [comment]
Thanks for sharing this, unfortunately didn't notice your comment. I am not sure if your approach would work in betterC scenarios, I will test it. I found a different workaround, the original function names should now wok again, but if you still get collisions you can use the same functions with an Ext post-fix, e.g. `loadDeviceLevelFunctionsExt`. More details can be found [here in the second paragraph](https://github.com/ParticlePeter/ErupteD#platform-extensions). Try any version including and above v2.1.0+v1.2.150.
