### ISSUE TITLE
Importing erupted.vulkan_lib_loader and import erupted.platform_extensions with mixin causes error.

### ISSUE THREAD

**Issue by kyle-vasilia** [ParticlePeter/ErupteD#19]
Hello. 
Is there a recommended way to do this, because on the outer scope level I import a package that's

>module window;
>public import core.sys.windows.windows;
>import erupted.platform_extensions;
>mixin Platform_Extensions!USE_PLATFORM_WIN32_KHR;

and 
>erupted.vulkan_lib_loader
spits out this error about functions using same name 
>source\app.d(127,28): Error: function window.Platform_Extensions!(KHR_win32_surface, KHR_external_memory_win32, KHR_win32_keyed_mutex, KHR_external_semaphore_win32, KHR_external_fence_win32, NV_external_memory_win32, NV_win32_keyed_mutex, EXT_full_screen_exclusive).loadInstanceLevelFunctions at C:\Users\Vasilia\AppData\Local\dub\packages\erupted-2.0.70_v1.2.150\erupted\source\erupted\platform_extensions.d(1084,10) conflicts with function erupted.functions.loadInstanceLevelFunctions at C:\Users\Vasilia\AppData\Local\dub\packages\erupted-2.0.70_v1.2.150\erupted\source\erupted\functions.d(1001,6)
source\app.d(184,26): Error: function window.Platform_Extensions!(KHR_win32_surface, KHR_external_memory_win32, KHR_win32_keyed_mutex, KHR_external_semaphore_win32, KHR_external_fence_win32, NV_external_memory_win32, NV_win32_keyed_mutex, EXT_full_screen_exclusive).loadDeviceLevelFunctions at C:\Users\Vasilia\AppData\Local\dub\packages\erupted-2.0.70_v1.2.150\erupted\source\erupted\platform_extensions.d(1253,10) conflicts with function erupted.functions.loadDeviceLevelFunctions at C:\Users\Vasilia\AppData\Local\dub\packages\erupted-2.0.70_v1.2.150\erupted\source\erupted\functions.d(1464,6)  `

My solution was to have them have different import names aka "import foo = file.module;" and even still that throws the error.
`saun-vk-examples.obj : fatal error LNK1179: invalid or corrupt file: duplicate COMDAT 'loadDeviceLevelFunctions'
Error: linker exited with status 1179
dmd failed with exit code 1.` 

What's behind this? am I supposed to import these in different places and not on the outer scope?

**Comment by kyle-vasilia** [comment]
Extra information. 

I copied over `vulkan_windows.d` over to my project and didn't even import it to the main code and it throws LNK1179 aswell

Looks like `Platform_Extensions!USE_PLATFORM_WIN32_KHR;` gives off this linker error for some reason

**Comment by kyle-vasilia** [comment]
Fixed it, solution I found is to only do mixin when it's needed
etc:
>vkGetDeviceQueue(device, queueGfx, 0, &gfxQueue);
>mixin Platform_Extensions!USE_PLATFORM_WIN32_KHR;
>VkWin32SurfaceCreateInfoKHR test;
Hope that helps anyone else looking.

**Comment by ParticlePeter** [comment]
Thanks for posting your issue and a workaround. For what it's worth, this issue pops up in my projects as well, but only recently. I my self didn't find a solution so far but assume a dmd bug, even though it is a linker error. I think I can work around the issue by simply renaming those mixed in functions to something like `loadExtendedInstanceLevelFunctions`. I'll inform you here when this happens.

This is how it woks: The mixin instantiates `loadInstanceLevelFunctions` and `loadDeviceLevelFunctions` which include your requested extensions. Functions with the same name, excluding your requested extensions, already exist in module erupted.functions, the mixed in ones even call those.
So, after mixin instantiation, we have some function pairs with the same name and signature, but in different modules and hence they should not collide. The linker begs to differ, even if we use the full module path (and even if we instantiate, but do not use the mixed in ones, which is even weirder).

You also asked how to use the mixin. The original working idea was to actually use the `vulkan_window.d` module as is, and import it where ever you need the extended functionality. From your solution I see that you mixed the platform extension into your vulkan runtime/setup code. I wouldn't recommend doing this, as you might need those functions in some other module. When this happens, you should not re-instantiate that mixin. If you do, your best case scenario is a bloated executable, worst is more compile/linker issues.

**Comment by kyle-vasilia** [comment]
Going to re-open for future reference as getting compiler/linker errors as you foresaw.

**Comment by ParticlePeter** [comment]
I think I successfully worked around the issues, in the way as explained above. The original function names should now wok again, but if you still get collisions you can use the same functions with an Ext post-fix, e.g. `loadDeviceLevelFunctionsExt`. More details can be found [here in the second paragraph](https://github.com/ParticlePeter/ErupteD#platform-extensions). Try any version including and above v2.1.0+v1.2.150.

**Comment by ParticlePeter** [comment]
Can this be closed?

**Comment by JackStouffer** [comment]
I think the documentation on this could be clearer. I'm still having trouble trying to incorporate the Windows platform stuff into the devices example.
