### ISSUE TITLE
Pure, nothrow and @nogc should be relaxed for the debug callback

### ISSUE THREAD

**Issue by MaikKlein** [ParticlePeter/ErupteD#2]
https://github.com/ParticlePeter/ErupteD/blob/master/source/erupted/types.d#L12

https://github.com/ParticlePeter/ErupteD/blob/master/source/erupted/types.d#L3549

It makes it quite useless, I think it should only be nothrow.

**Comment by ParticlePeter** [comment]
The callback is a C construct and the attributes describe that. Throwing is not possible and the GC not available in C. `pure` is not a C feature, I just thought its would be useful but I am not sure anymore. I think it should be removed.
`nothrow` should not be a problem as you can always use a `try` / `catch` block around throwing functions inside the callback (but I would not recommend using throwing functions).
I think `@nogc` should stay as well, I doubt that you want to allocate at all in such a callback, you can pass memory through the pUserData pointer. However, if you must allocate why not allocate without the GC (e.g. with [scoped!class](https://dlang.org/phobos/std_typecons.html#.scoped) or [std.container](http://dlang.org/phobos/std_container.html) or simply malloc)?.

**Comment by MaikKlein** [comment]
I wanted it @nogc because there are still some functions in the std that use the gc. For example writeln is still not @nogc because it throws an exception. Not sure if you can work around that.

**Comment by ParticlePeter** [comment]
You can with printf (core.stdc.stdio). It's not so confortable as writeln but it gets the Job done.

**Comment by MaikKlein** [comment]
This works for me

```
        {
            "name"          :   "dub-platform-xcb",
            "versions"      :   [ "VK_USE_PLATFORM_XCB_KHR" ],
            "dependencies"  :   {
                "xcb-d"         : "~>1.11.1"
            },

```

```
        {
            "name"          :   "dub-platform-xcb-derelict-loader",
            "versions"      :   [ "VK_USE_PLATFORM_XCB_KHR", "ERUPTED_FROM_DERELICT" ],
            "dependencies"  :   {
                "xcb-d"         : "~>1.11.1",
                "derelict-util" : "~>2.0.4"
            },

```

So that xcb in xlib and erupted have the same dependencies. I think that is a more general bug in dub though.

**Comment by MaikKlein** [comment]
Out of curiosity are you able to use debug messages? Whenever I print `printf(pMessage)` it crashes with -11, which is strange. I have looked up the signature and your debug function signature looks correct, not sure what is happening.

At least it gets called correctly.

And its not my driver, other examples from cpp are working just fine, I am not 100% sure what is going on.

**Comment by ParticlePeter** [comment]
Your first message seems to belong to issue #3 

Your second message, yes I think the callbacks should have either extern(C) or extern(System) linkage. Lets try the later first.

**Comment by ParticlePeter** [comment]
Uploaded a new Version, please test.

**Comment by MaikKlein** [comment]
I added it to my local version of erupted and `extern(System)` indeed works.

**Comment by ParticlePeter** [comment]
I'll look into it, but Need some time.

**Comment by ParticlePeter** [comment]
I am fully confused by the way. Please don't reference wrongly posted issues. Remove the post here and post it again where it belongs..
