### ISSUE TITLE
A typo

### ISSUE THREAD

**Issue by jordan4ibanez** [ParticlePeter/ErupteD#25]
There is a typo on line 38 of types.d "derectated". I have tried to do a PR twice but github is making the commit as if I rewrote the entire file.

**Comment by ParticlePeter** [comment]
Thanks, noticed myself before noticing this issue :-) it's fixed from [v2.1.88+v1.3.238](https://github.com/ParticlePeter/ErupteD/releases/tag/v2.1.88%2Bv1.3.238) upwards.
