### ISSUE TITLE
All uses of `const type*` should be replaced with `const(type)*`

### ISSUE THREAD

**Issue by AndrejMitrovic** [ParticlePeter/ErupteD#5]
I think you already know this (judging from erupt.py code I saw), in C `const type*` means _pointer to constant type_, in D it means _constant pointer to constant type_. The parentheses are needed to match the C semantics.

There's at least one function which is defined as:

```
alias PFN_vkDebugReportCallbackEXT = VkBool32 function(VkDebugReportFlagsEXT flags, VkDebugReportObjectTypeEXT objectType, uint64_t object, size_t location, int32_t messageCode, const char* pLayerPrefix, const char* pMessage, void* pUserData);
```

Notice the `const char*`.

In fact I think it's the only one left to fix? :)

**Comment by ParticlePeter** [comment]
You're right of course, will fix it for the sake of correctness. However, I am successfully using the callback in its current state, I guess Vulkan is calling it through the c runtime?

**Comment by AndrejMitrovic** [comment]
Oh it will continue to work, it just makes it a bit less convenient from the D side. :)

**Comment by ParticlePeter** [comment]
Fixed in the latest release.

**Comment by AndrejMitrovic** [comment]
Cool stuff, thank you!
