### ISSUE TITLE
DispatchDevice is private to the erupted.functions module.

### ISSUE THREAD

**Issue by MrPeteypoo** [ParticlePeter/ErupteD#9]
Hi there, thanks for creating this library, I've found it really helpful in my University work. Unfortunately there's an issue with one of your proposed device-level function loading mechanisms.

If I want to create a "Renderer" class/struct which works a given logical device, directly calls device-level functions but doesn't override the global functon poiners, I have to use "createDispatchDeviceLevelFunctions()". It returns a struct of function pointers which is fine, the issue is if I want to keep that struct as a member of a class/struct I need to either selectively import it or use a workaround to account for the fact that DispatchDevice has actually been marked private to the module!

Some example code:
```d
import erupted.functions;
import std.traits;

struct BrokenSingleDeviceRenderer
{
    DispatchDevice deviceFuncs; // Fails to compile, DispatchDevice is marked as private.
}

struct WorkingSingleDeviceRenderer
{
    auto deviceFuncs = ReturnType!(createDispatchDeviceLevelFunctions)(); // Compiles.

    // The deviceFuncs member is an instance of DispatchDevice.
    pragma (msg, typeof (deviceFuncs)); 
}

struct AnotherWorkingSingleDeviceRenderer
{
    import erupted.functions : DispatchDevice;
    DispatchDevice deviceFuncs; // Compiles thanks to selective importing.
}
```

Would it be possible to remove the private access modifier as I'm not sure what benefit there is to having it marked as private? Is there a use-case I'm missing that requires the private modifier?

Thanks.

**Comment by ParticlePeter** [comment]
Reason for private Dispatch_Device is that if you simply create the struct the function pointers are not loaded and the Dispatch_Device would not work. I wanted to avoid this scenario, hence the creation function. Unfortunately I have not anticipated your case. Btw, I think that both of your working examples should not work, wired.

I will look into this the next days, at first glance this here should satisfy both of us, what you think?

```
struct DispatchDevice {
    @disable this();
    this( VkDevice vkDevice ) {
        // load functions
    }
    // PFN_function members
```

**Comment by MrPeteypoo** [comment]
The examples compile on DMD 2.072.2 and 2.074.0 and LDC2 1.1.1. I'm not sure whether being able to selectively import private symbols is a language bug or intended behaviour tbh. Using the ReturnType!() trick is probably similar to template trickery in C++ where you can gain access to private nested classes/structs.

Anyway, in regards to your suggestion it would work but still has a drawback which I think may be worse than the current issue. You could have a DispatchDevice member inside a class/struct but it would force the default constructor of the containing class/struct to be disabled as well.

```d
struct Bob
{
    @disable this();
    this (VkDevice device)
    {
        import std.stdio;
        writeln("BOB!");
    }
}
struct Sam
{
    // Requires Sam to have a custom constructor which initialises bob.
    Bob bob; 
    this(VkDevice device)
    {
        bob = Bob(device);
    }
}
Sam sam; // Error: default construction is disabled for type Sam.
```

**Comment by ParticlePeter** [comment]
This is true and was also intended, I would prefer not creating uninitialized Dispatch Devices.

I also don't see the issue with your example above. You have to initialize the device at some time, so why not before constructing your renderer? Could you give me an example where you think it wouild not be possible to pass the VkDevice through the renderer to the Dispatch Device?
Please also consider:
If your renderer is a struct, its member could be Dispatch_Device pointer.
If its a class you could overwrite the default constructor and initialize the VkDevice of the Dispatch_Device there.

Wouldn't that work?

**Comment by MrPeteypoo** [comment]
The issue is that it would dictate architectural choices of anyone that uses it. Although I prefer to initialise objects in constructors, it's quite common for game engines to take an alternative approach. A common alternative is having some kind of initialise() method on structs/classes which is where the real initialisation takes place as it allows any struct/class to hold anything and the engine gains more control over initialisation order. Disabling the default constructor would prevent this from being possible. In that case I think disabling the default constructor would be worse than having it be private in the first place. 

I feel the nature of the library and the available usage instructions are clear enough that the responsibility for making sure the DispatchDevice object is initialised should be on the programmer using the library. That way you aren't dictating architectural decisions of client applications and they can still take advantage of having device-level functions scoped inside a struct. If that still doesn't rest well with you then I would probably leave it as private, that way the programmer has to explicitly include it in they want to use it.

Hope this helps.

**Comment by ParticlePeter** [comment]
I came to a similar conclusion after on nights sleep. Vulkan is about giving the user all the responsibility so should Erupted. Moreover I also hate wrestling with other ones APIs. O.K. it will be done in the next minor release.

**Comment by MrPeteypoo** [comment]
Thanks, that would be good! Keep up the good work! 👍

**Comment by ParticlePeter** [comment]
Thanks, its done. As you are the only user that I know of of the DispatchDevice, could you please test the convenience functions as described [here](https://github.com/ParticlePeter/ErupteD#dispatchdevice) and comment?

**Comment by MrPeteypoo** [comment]
I'm using Erupted to do my final year project and the deadline is quite soon so I don't really have time right now to change my approach so I don't know when I'll get chance to test your new implementation. I ended up creating a Device struct which is a wrapper for a device and device-level functions with some extra data like queues and such. I used opDispatch to forward device-level functions calls to the correct function in the DispatchDevice, similar to what you've done but without explicitly writing the wrapping function. I didn't think about removing the "vk" prefix though, tis a good idea I might try myself!

https://github.com/storm20200/Denjin/blob/master/packages/rendering/source/denjin/rendering/vulkan/device.d

**Comment by ParticlePeter** [comment]
Yes, take your time. My master thesis is due soon as well, so lets talk later.
Btw, I would have preferred to keep the vkPrefix, but I do not manage to make it work. Tried opDispatch as well, but it seems that you cannot overload a function pointer with a regular function. And I did not want to wrap the fp in a regular function with same parameters which would imply one more indirection.

**Comment by MrPeteypoo** [comment]
I had that issue too, the trick was to have an opDispatch nested in a template opDispatch which has a template constraint on it. That seems to override global functions and takes priority 👍

**Comment by ParticlePeter** [comment]
Ah, that was the reason. I honestly did not understand what you did there and why. But then again we need to ask if this works due to a bug or feature. Anyway I think I'll stick with the 'no-vk-prfix' variant to distinct from the 'real' vulkan functions. Nice and clean coding style btw. I'll keep an eye on your project.

**Comment by ParticlePeter** [comment]
Can this be closed?

**Comment by MrPeteypoo** [comment]
Yeah feel free to close it, I don't get much time for personal projects anymore :(
